### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by Zeroto521** [Flow-Launcher/flow-launcher.github.io#16]
![image](https://user-images.githubusercontent.com/25895405/111284979-a3139100-867b-11eb-86dc-f33539cc9765.png)

![image](https://user-images.githubusercontent.com/25895405/111285074-b9215180-867b-11eb-983d-44b847c46a7f.png)

Is the github page setting's branch `gh-pages`?

**Comment by jjw24** [comment]
thats weird, why is the gh pages setting turned off??

![image](https://user-images.githubusercontent.com/26427004/111286503-5f7a5080-8696-11eb-9acd-951b51328ccc.png)

**Comment by jjw24** [comment]
Good pick up @Zeroto521 👍

**Comment by jjw24** [comment]
strange, after the deployment, it's changed again:
![image](https://user-images.githubusercontent.com/26427004/111290619-702cc580-869a-11eb-8ca4-340fac33ef2e.png)

**Comment by jjw24** [comment]
hmmmm something is up, after putting in PR 18:
![image](https://user-images.githubusercontent.com/26427004/111296222-57bfa980-86a0-11eb-8c6b-f261e1fdf590.png)

@Zeroto521 is it the github workflow?

**Comment by Zeroto521** [comment]
Well, it seems that we couldn't check the commit history of `gh-pages` after this branch was deleted.

What event could delete the `gh-pages`? 

But we need to turn up the gh pages setting again.

**Comment by Zeroto521** [comment]
Actually, I have a question.

Why you directly **edit** & pr rep instead of **forking** & pr?

**Comment by jjw24** [comment]
> Actually, I have a question.
> 
> Why you directly **edit** & pr rep instead of **forking** & pr?

There is no need for forking if you have write access, which all of us in the team do. So I just create a separate branch and pr.

Very rare occasions I will directly edit, only if it's a simple text change that I really don't think need to be reviewed, eg. Changing 'search flow's to 'find flow', and I only do this on md files such as readmes.

**Comment by jjw24** [comment]
> Well, it seems that we couldn't check the commit history of `gh-pages` after this branch was deleted.
> 
> What event could delete the `gh-pages`?
> 
> But we need to turn up the gh pages setting again.

Not sure yet, maybe due to me ticking the option to delete head branches after merge, will test it out

**Comment by jjw24** [comment]
Seems resolved after unchecking in settings:
![image](https://user-images.githubusercontent.com/26427004/111864628-459e7d80-89b6-11eb-9a47-f7c179baf4d3.png)
