### ISSUE TITLE
[discuss] how to deploy the website

### ISSUE THREAD

**Issue by Zeroto521** [Flow-Launcher/flow-launcher.github.io#2]
I had an idea. But I don't know it is possible or not.

we have _Flow.Launcher.Website_ and _Flow-Launcher.github.io_, two projects.

we use _Github Action_ to build the source code to _Flow-Launcher.github.io_ master branch when _Flow.Launcher.Website_ master branch has any pull requests.

**Comment by Zeroto521** [comment]
I should build two projects then have a test.

**Comment by Xenolphthalein** [comment]
There is already a workflow available for github actions: https://github.com/analythium/github-pages-quasar
Specifically this file: https://github.com/analythium/github-pages-quasar/blob/master/.github/workflows/build.yml
I'm going to test it in my github accouont and will tell you once i have the results.

**Comment by Zeroto521** [comment]
A simple way is that just use the _Flow.Launcher.Website_ one project is fine.
Let the Action to build the master branch to _deploy_ branch (or another name).
Then we can make the _deploy_ branch show the website.

**Settings / GitHub Pages** as follows.

![image](https://user-images.githubusercontent.com/25895405/101341755-84537080-38bc-11eb-90f3-f998098d51c9.png)

This way may get easier. This way was inspired by my colleague.

---

> we use Github Action to build the source code to Flow-Launcher.github.io master branch when Flow.Launcher.Website master branch has any pull requests.

I used the Github Page service two years ago.
Two years ago, the project name must be _Flow-Launcher.github.io_ if you use this service. 
Something is different from my memory.

**Comment by jjw24** [comment]
what about just renaming this repo to Flow-Launcher.github.io? and then keep source code in master and point to a branch for the website, so we can just use Flow-Launcher.github.io

**Comment by Zeroto521** [comment]
> what about just renaming this repo to Flow-Launcher.github.io? and then keep source code in master and point to a branch for the website, so we can just use Flow-Launcher.github.io

Change or not, it's no matter.
The GitHub Page is useful for any GitHub repository. 
You can check the image in last comment.
Or see the project **settings** page.
Now we just write a GitHub action .yml file to compile the source codes to another branch. Finish this step, we need your help to set it project settings page.

Settings link is here https://github.com/Flow-Launcher/Flow.Launcher.Website/settings

**Comment by jjw24** [comment]
Isnt it if you do it on project level, the site url is going to be  orgusername.github.io/projectname as oppose to doing it on organisational level the url will be orgusername.github.io?

Thought flow-launcher.github.io url is more ideal than flow-launcher.github.io/flow.launcher.website ?

**Comment by jjw24** [comment]
yeah so as I figured, without renaming the repo we get a project site with url 'flow-launcher.github.io/Flow.Launcher.Website'
![image](https://user-images.githubusercontent.com/26427004/102127682-e570da80-3ea0-11eb-8ca1-78a47e294be8.png)
Which also doesnt work properly:
![image](https://user-images.githubusercontent.com/26427004/102127838-1c46f080-3ea1-11eb-8828-a635eee0ec96.png)



After renaming, the site url is now https://flow-launcher.github.io

Good work guys 👍 💯

**Comment by jjw24** [comment]
btw i feel like the query box on the website is oddly small compared to the actual page, what do you think?

**Comment by Xenolphthalein** [comment]
I oriented myself on the size the launcher would have on a normal full hd desktop. Of course we can scale that up a notch if you like.

EDIT: Great work rolling it out btw. 👍

**Comment by Zeroto521** [comment]
By the way, another deploying method.

_Flow.Launcher.Website_ deploys to https://flow-launcher.github.io/Flow.Launcher.Website, and _Flow-Launcher.github.io_ project just adds one file called `index.html`. let it redirect from `/` to `/Flow.Launcher.Website`

**Comment by jjw24** [comment]
good to know. Think currently it's fine, unless there is a reason not to name this repo flow-launcher.github.io

**Comment by jjw24** [comment]
> I oriented myself on the size the launcher would have on a normal full hd desktop. Of course we can scale that up a notch if you like.

hmm what do you think @Zeroto521 ?

**Comment by Zeroto521** [comment]
Does this mean the website or flow desktop?

**Comment by jjw24** [comment]
The query box on the website, do you think it's small compared to the rest of the layout?

**Comment by Zeroto521** [comment]
![image](https://user-images.githubusercontent.com/25895405/102161311-11508800-3ec2-11eb-9369-ca6d854dde36.png)

compared to the desktop flow, actually, it is

**Comment by Zeroto521** [comment]
![image](https://user-images.githubusercontent.com/25895405/102161474-5d9bc800-3ec2-11eb-9add-f6184e716b44.png)

the same length is fine

**Comment by jjw24** [comment]
i will close this for now, see the feedback.
