### ISSUE TITLE
Add sponsor Appwrite

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/flow-launcher.github.io#30]
Add sponsor Appwrite to our website. 
Assets can be found: https://appwrite.io/assets

**Comment by jjw24** [comment]
Hi @softwareengineerofficial how's it going? Since you mentioned in your previous issue, would you be keen to help add our sponsor Appwrite to the website?

**Comment by iam-gopi** [comment]
> Hi @softwareengineerofficial how's it going? Since you mentioned in your previous issue, would you be keen to help add our sponsor Appwrite to the website?

Yes of course tell me what to do?

**Comment by jjw24** [comment]
Awesome, thank you.

Add a 'Sponsor' section to the bottom of the page, something like this:
![image](https://user-images.githubusercontent.com/26427004/183086532-7d0d219e-2bdf-432c-b08e-62cd4c645d8d.png)


With a link to appwrite's website via their logo, and a link to our github sponsor page.

**Comment by jjw24** [comment]
Obviously also adjust it however you see fit or think is better 🙂

**Comment by iam-gopi** [comment]
I will work on it. You can assign this to me

**Comment by iam-gopi** [comment]
@jeremymeyers changes done. kindly have a look [PR](https://github.com/Flow-Launcher/flow-launcher.github.io/pull/31)

Any thoughts let me know.

**Comment by jjw24** [comment]
Thanks @softwareengineerofficial.

- Would it be possible to still show the waves by reducing the gap above the 'Sponsors' section?
- Instead of black font colour for 'Become a sponsor' maybe the same grey colour like in the screenshot
- Could we move 'Become a sponsor to blow Appwrite please

**Comment by iam-gopi** [comment]
@jjw24 find the status below. I did two points but the third one is not understandable. Can you please elaborate on it?

NOTE: PR is updated.

* Would it be possible to still show the waves by reducing the gap above the 'Sponsors' section? - **completed**
* Instead of the black font colour for 'Become a sponsor' maybe the same grey colour as in the screenshot - **completed**
* Could we move 'Become a sponsor to blow Appwrite, please - **_not getting this point_**

**Comment by jjw24** [comment]
Hey @softwareengineerofficial thanks for making the changes. For the third point I mean move 'Become a sponsor' to below the 'Sponsor section' like this, and additional having the waves still visible:

![image](https://user-images.githubusercontent.com/26427004/183624644-991cf01f-e0bc-4604-8d8c-5207df8e583a.png)

**Comment by iam-gopi** [comment]
@jjw24 changes are done and PR is updated. 
* Become a sponsor moved below
* Wave is still visible. 

Anything else let me know will work on it

**Comment by jjw24** [comment]
Hey thanks for the changes, The wave is still hidden as in having to scroll down to see it, here is what it looks like (I merged your changes into my fork and deployed via page actions) https://jjw24.github.io/flow-launcher.github.io/.

**Comment by iam-gopi** [comment]
Hi @jjw24 here is the video that I recorded from the above link [https://youtu.be/UvDLgkJZfd0](https://youtu.be/UvDLgkJZfd0)

If you don't like the video on Youtube tell me I'll remove it

**Comment by jjw24** [comment]
Hey no problems at all with the video.

Have you had a chance to update it again so it's all on one page without the need to scroll (for browsers)?

**Comment by iam-gopi** [comment]
Is this look fine?
![image](https://user-images.githubusercontent.com/18674571/184478853-d4cc872c-5580-4719-b35e-748caa93dcef.png)

**Comment by jjw24** [comment]
Is it because of the sponsor section too large i.e. font size that they can't fit on one page? Could we reduce the font size for sponsors or move the section up a bit more?

**Comment by iam-gopi** [comment]
this is the max I could reduce else it won't look good. Check this and let me know how to proceed further. 
**_NOTE:_** Code is not pushed yet. 
![image](https://user-images.githubusercontent.com/18674571/184504416-2e8678fd-5e36-4238-9738-c3181e606489.png)

**Comment by jjw24** [comment]
Hmm can you push your changes up please and then in another new commit remove entirely 'Become a sponsor', let's see if that will bring the waves up a bit more.

**Comment by iam-gopi** [comment]
@jjw24  I pushed my changes if you suppose wanted to remove Become a Sponsor option, I do have an idea. instead of removing the why don't we keep the link near to the Sponsor heading as like the below example.

**Sponsor | _Become a Sponsor_**

**Comment by jjw24** [comment]
Actually good suggestion but let's just have the 'Sponsor' title linked instead so it's cleaner.

**Comment by iam-gopi** [comment]
@jjw24 actually a good idea. I did the changes and pushed kindly have a look

**Comment by jjw24** [comment]
We are getting very close. There is a huge chunk of whitespace at the bottom: 
https://jjw24.github.io/flow-launcher.github.io/

Could we move the waves back down to the bottom and have the 'Sponsor' section in the middle between the top part and bottom waves like below:
![image](https://user-images.githubusercontent.com/26427004/184723492-6cf0fbd3-4909-4fc3-b3b6-b752420038e1.png)

**Comment by iam-gopi** [comment]
@jjw24 sorry for the late response little occupied with other client work. I did see any space in the waves. can you kindly let me know where the space is exactly?

**Comment by jjw24** [comment]
Hey no worries take your time. I realised the screenshot doesn't show it against a white background but if you go to that link you will be able to see the white space below the waves on a computer browser.

**Comment by iam-gopi** [comment]
@jjw24 I fixed that white space now. got busy with work so got it late. PR updated with the fix

**Comment by jjw24** [comment]
Hey I checked it out, still has the white space - https://jjw24.github.io/flow-launcher.github.io/

**Comment by jjw24** [comment]
Hi @softwareengineerofficial, have you had a chance to take another look at the white space issue?

**Comment by iam-gopi** [comment]
@jjw24 really sorry for not updating you. I was in the hospital with my mother for her check-up. it dragged for a week plus. I'll complete this today and will share with you.

**Comment by jjw24** [comment]
Hey @softwareengineerofficial, sorry to hear and hope her check up went all ok. No stress, family is important. If you like I can take over and fix that issue?

**Comment by iam-gopi** [comment]
@jjw24 the empty space at the end was fixed and also I modfied the scroll bar check if its okay for you. if not will remove it. PR updated.

I tested the emprty space issue with Chrome, Edge & Firefox browsers

**Comment by iam-gopi** [comment]
@jjw24 is the above fix fine?

**Comment by jjw24** [comment]
Hey @softwareengineerofficial merged, thank you.
