### ISSUE TITLE
Width changes when query box is empty

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/flow-launcher.github.io#4]
the query box on the website changes width when emptied.

repro:
clear the query box
enter any character

see the width change slightly

**Comment by Xenolphthalein** [comment]
![flowlauncher](https://user-images.githubusercontent.com/21215869/102894456-6b71c000-4463-11eb-8f7b-e7167bb872b4.gif)

I can't seem to reproduce this issue :thinking: 
Edit: Tried it with Firefox, Vivaldi and Chrome
